var data, i, options, r, scatter, val, x, xaxis, y, yaxis;

r = new Bokeh.Random(123456789);

x = (function() {
  var _i, _len, _ref, _results;
  _ref = _.range(4000);
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    _results.push(r.randf() * 100);
  }
  return _results;
})();

y = (function() {
  var _i, _len, _ref, _results;
  _ref = _.range(4000);
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    _results.push(r.randf() * 100);
  }
  return _results;
})();

data = {
  x: x,
  y: y,
  radius: (function() {
    var _i, _len, _ref, _results;
    _ref = _.range(4000);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      _results.push(r.randf() + 0.3);
    }
    return _results;
  })(),
  color: (function() {
    var _i, _len, _ref, _results;
    _ref = _.zip(x, y);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      val = _ref[_i];
      _results.push("rgb(" + (Math.floor(50 + 2 * val[0])) + ", " + (Math.floor(30 + 2 * val[1])) + ", 150)");
    }
    return _results;
  })()
};

scatter = {
  type: 'Circle',
  source: "mydata",
  x: 'x',
  y: 'y',
  radius: 'radius',
  fill_color: 'color',
  fill_alpha: 0.6,
  line_color: null
};

options = {
  title: "Scatter Demo",
  plot_width: 100,
  plot_height: 100,
  x_range: [0, 100],
  y_range: [0, 100]
};

xaxis = {
  type: "auto",
  location: "below",
  grid: true
};

yaxis = {
  type: "auto",
  location: "left",
  grid: true
};

Bokeh.$(function() {
  $("#bkplot").bokeh("figure", {
  options: options,
  sources: {
    mydata: data
  },
  glyphs: [scatter],
  guides: [xaxis, yaxis],
  tools: ["Pan", "WheelZoom", "Resize", "Reset"]
});
})


// ---
// generated by coffee-script 1.9.0